const LABEL_TYPE = Object.freeze({
  GOTO_START_WHILE: 'GOTO_START_WHILE',
  GOTO_END_WHILE: 'GOTO_END_WHILE',
  WHILE_LOOP: 'WHILE_LOOP',
  END_WHILE: 'END_WHILE',
  GOTO_IF_TRUE: 'GOTO_IF_TRUE',
  GOTO_IF_FALSE: 'GOTO_IF_FALSE',
  GOTO_END_IF: 'GOTO_END_IF',
  IF_TRUE: 'IF_TRUE',
  IF_FALSE: 'IF_FALSE',
  END_IF: 'END_IF',
  DEF: 'DEF',
  END_DEF: 'END_DEF',
  METHOD_CALL: 'METHOD_CALL',
  METHOD_PARAM: 'METHOD_PARAM',
  METHOD_RETURN: 'METHOD_RETURN',
});
export default LABEL_TYPE;
